### ISSUE TITLE
安装后tabby的重连功能无法正常工作

### ISSUE THREAD

**Issue by z0ow** [trzsz/tabby-trzsz#1]
tabby的重新连接会卡住，卸载trzsz插件后正常

**Comment by lonnywong** [comment]
感谢反馈。

是什么操作系统？tabby是哪个版本的？

“重新连接”具体是怎么操作的？我比较少用 tabby ，不是很熟悉。是指关了 tabby 后，重新打开 tabby，它会自动连接之前的 session，这个“重新连接”？

**Comment by z0ow** [comment]
是的。windows系统，tabby 1.0.183, trzsz 插件0.3.3最新版本。
![image](https://user-images.githubusercontent.com/20352723/188528918-6fb5fc16-a413-4821-a416-2546ac623f63.png)

在tabby上方还有reconnect按钮，有时连接断开后需要重新连接也需要用到这个功能（可以保留历史信息），如果点击一下就会在下图这里卡住。
![image](https://user-images.githubusercontent.com/20352723/188529179-61b22512-a280-4ffd-a97d-1755d3797e01.png)

**Comment by z0ow** [comment]
tabby官方仓库issue也有关于卸载trzsz插件后tabby恢复正常的讨论 https://github.com/Eugeny/tabby/issues/6409

这个功能非常好用，希望能够得到有效修复，万分感谢~

**Comment by lonnywong** [comment]
需要等连接自己断开之后，再 reconnect 吗？

有没有办法让连接快速断开？（ 这个没有也行，我抽空看看怎么复现。）

**Comment by z0ow** [comment]
> 需要等连接自己断开之后，再 reconnect 吗？
> 
> 有没有办法让连接快速断开？（ 这个没有也行，我抽空看看怎么复现。）

可以不用等待连接断开，目前看来只要是reconnect行为都能触发这个bug，可以在连接保持的时候直接点击Reconnect按钮，一样能够复现

**Comment by lonnywong** [comment]
我复现出来了，会抽空解决这个问题（ 要周末才有空搞 ）。再次感谢。

**Comment by z0ow** [comment]
> 我复现出来了，会抽空解决这个问题（ 要周末才有空搞 ）。再次感谢。

辛苦啦，谢谢帮助！👏

**Comment by lonnywong** [comment]
版本 `v0.3.4` 已修复重连的问题。

**Comment by z0ow** [comment]
已安装最新0.3.4版本，该问题已经不存在了，非常感谢！

**Comment by KbyteTutu** [comment]
啊 早知道我在这边提issue了。。。
