### ISSUE TITLE
tabby插件点击获取，一直转圈圈，有什么好的办法吗

### ISSUE THREAD

**Issue by xhsdasd** [trzsz/tabby-trzsz#3]

**Comment by lonnywong** [comment]
有没有一个能连上外网的环境？可以从另外一台机器安装后，找出来复制过去。

https://github.com/Eugeny/tabby/discussions/6149

**Comment by xhsdasd** [comment]
我得机器是云服务器 是可以连上外网的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lonny ***@***.***&gt;; 
发送时间: 2022年10月18日(星期二) 下午2:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [trzsz/tabby-trzsz] tabby插件点击获取，一直转圈圈，有什么好的办法吗 (Issue #3)





 
有没有一个能连上外网的环境？可以从另外一台机器安装后，找出来复制过去。
 
Eugeny/tabby#6149

**Comment by lonnywong** [comment]
1、找一个目录，先下载：
```sh
mkdir tabby_plugin
cd tabby_plugin
npm init -y
npm i tabby-trzsz
```

2、打开 tabby，Settings -> Plugins -> Plugins folder，打开插件的目录。里面应该有个 node_modules 目录，没有的话可以新建一个。

3、在第一步那个目录里 node_modules 下，把 tabby-trzsz 和 trzsz 这两个目录复制到 tabby 插件目录的 node_modules 里。然后重启 tabby 应该就可以了。

**Comment by xhsdasd** [comment]
感谢 安装上去了 但是好像识别不到命令&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lonny ***@***.***&gt;; 
发送时间: 2022年10月18日(星期二) 下午3:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [trzsz/tabby-trzsz] tabby插件点击获取，一直转圈圈，有什么好的办法吗 (Issue #3)





 
1、找一个目录，先下载：
 mkdir tabby_plugin cd tabby_plugin npm init -y npm i tabby-trzsz
 
2、打开 tabby，Settings -&gt; Plugins -&gt; Plugins folder，打开插件的目录。里面应该有个 node_modules 目录，没有的话可以新建一个。
 
3、在第一步那个目录里 node_modules 下，把 tabby-trzsz 和 trzsz 这两个目录复制到 tabby 插件目录的 node_modules 里。然后重启 tabby 应该就可以了。

**Comment by lonnywong** [comment]
我这样安装是可以的，不过可能是我之前安装过的原因。

你在 Plugins 里找到 trzsz ，先 Disable 禁用它，重启，再 Enable 启用它，重启，看看可不可以？

**Comment by xhsdasd** [comment]
能否截图下 您的tabby 插件目录里面的目录结构 估计是bin找不到

**Comment by lonnywong** [comment]
tabby 不需要用 bin 里的命令的，只有服务器上需要安装 [trzsz](https://github.com/trzsz/trzsz) 或 [trzsz-go](https://github.com/trzsz/trzsz-go) （ 如果你是打开本地终端，那就是本地要另外安装，不关 tabby 的事了）。

```sh
tabby/plugins/
├── node_modules
│   ├── tabby-trzsz
│   │   ├── LICENSE
│   │   ├── README.md
│   │   ├── dist
│   │   └── package.json
│   └── trzsz
│       ├── LICENSE
│       ├── README.md
│       ├── bin
│       ├── lib
│       └── package.json
└── package-lock.json
```

**Comment by xhsdasd** [comment]
解决了 我服务器上没装trzsz 装了可以正常上传了 谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lonny ***@***.***&gt;; 
发送时间: 2022年10月18日(星期二) 下午3:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [trzsz/tabby-trzsz] tabby插件点击获取，一直转圈圈，有什么好的办法吗 (Issue #3)





 
tabby 不需要用 bin 里的命令的，只有服务器上需要安装 trzsz 或 trzsz-go （ 如果你是打开本地终端，那就是本地要另外安装，不关 tabby 的事了）。
 tabby/plugins/ ├── node_modules │&nbsp;&nbsp; ├── tabby-trzsz │&nbsp;&nbsp; │&nbsp;&nbsp; ├── LICENSE │&nbsp;&nbsp; │&nbsp;&nbsp; ├── README.md │&nbsp;&nbsp; │&nbsp;&nbsp; ├── dist │&nbsp;&nbsp; │&nbsp;&nbsp; └── package.json │&nbsp;&nbsp; └── trzsz │&nbsp;&nbsp;     ├── LICENSE │&nbsp;&nbsp;     ├── README.md │&nbsp;&nbsp;     ├── bin │&nbsp;&nbsp;     ├── lib │&nbsp;&nbsp;     └── package.json └── package-lock.json
