### ISSUE TITLE
拖拽文件上传

### ISSUE THREAD

**Issue by Wruins** [trzsz/tabby-trzsz#4]
os：windows
tabby：v1.0.197
trzsz-tabby：v1.0.1
已经开启了拖拽上传功能
我开两个命令行（两个不同的路径），我要在第一个命令行拖拽上传文件，第一个命令行没反应，第二个命令行在上传
即便我换了一下标签的位置，他仍然是第二次开的命令行里上传文件。
![image](https://github.com/trzsz/tabby-trzsz/assets/33518973/0b39c4c0-cd6e-4fd4-8f59-016a342f1944)

**Comment by lonnywong** [comment]
在不同的 tab ，非拖拽的方式，手工输入 trz 命令上传，这个没有错吧？

看来是这几行代码，取到了个错误的 middleware 对象了。
https://github.com/trzsz/tabby-trzsz/blob/e72c2e95c2259311c433f9577337950ab0013993/src/decorator.ts#L27-L34

等有空了，我研究一下看怎么可以取到正确的（ PS：不是很熟悉这个，或许可以问一问 tabby 的作者？）

**Comment by Wruins** [comment]
是的，命令上传没有问题。
上传有时候会超时，这个也可以看看，但是没太大影响，重新上传一边就好了

**Comment by lonnywong** [comment]
[Go 版](https://github.com/trzsz/trzsz-go) 实现了流水线作业式的传输，超时的问题应该是优化了，不过目前要求服务器和客户端都用 Go 版才生效。

tabby 要用 Go 版客户端的话，建议使用 [trzsz-ssh ( tssh )](https://github.com/trzsz/trzsz-ssh) ，需要先打开本地 shell，再用 `tssh xxx` 登录服务器。如果不经过本地 shell，直接登录远程服务器，则还是使用 tabby 插件的（ 即 js 版的 trzsz ）。

如果要拖拽上传的话，可以 `tssh --dragfile xxx` 这样登录，这个不会有 tabby 插件的这个问题。就是使用习惯上会有些不同。

Py 和 Js 版都还没空实现类似的功能，在网络不是很稳定的情况下，有可能会超时。现在默认超时时间是 20 秒，可以通过参数加长的，如 `trz -t 100` 就是 100 秒才超时。

**Comment by lonnywong** [comment]
@Wruins `v1.0.2` 应该修复这个问题了。
