### ISSUE TITLE
trz/tsz just stuck

### ISSUE THREAD

**Issue by 0smboy** [trzsz/tabby-trzsz#5]
Version: 1.0.201
Platform: macOS arm64 22.5.0
Plugins: trzsz 1.0.3
Frontend: xterm-webgl
<img width="630" alt="image" src="https://github.com/trzsz/tabby-trzsz/assets/91452062/f6e7b49e-4d2c-48f6-ad96-000d1872dcad">
<img width="676" alt="image" src="https://github.com/trzsz/tabby-trzsz/assets/91452062/ef3e642f-d576-4eab-a568-b82b58b5f558">
<img width="647" alt="image" src="https://github.com/trzsz/tabby-trzsz/assets/91452062/d2ee9d25-5cfa-499a-b488-92c75e203fc7">

**Comment by lonnywong** [comment]
How about upgrade tabby to `1.0.203`? It works on my `Mac M1, 14.0`.

What's `Frontend: xterm-webgl`? Is it a setting in tabby?

**Comment by 0smboy** [comment]
im sorry, there are something error in my dist package, it works when i rebuild the tabby-sftp-tab
