### ISSUE TITLE
无法安装，如图

### ISSUE THREAD

**Issue by hb-0** [trzsz/tabby-trzsz#6]
![image](https://github.com/trzsz/tabby-trzsz/assets/22149306/d25dc6f8-00c9-4716-bf1f-fc846277c4f7)

**Comment by lonnywong** [comment]
什么操作系统，什么版本的 tabby ?

**Comment by hb-0** [comment]
感谢回复，看了https://github.com/trzsz/tabby-trzsz/issues/3
解决了

> 什么操作系统，什么版本的 tabby ?
